name: Java CI with Gradle

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - 
      name: Set up JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '17'
        distribution: 'oracle'
    - 
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2.7.0
    - 
      name: Execute Gradle build
      run: ./gradlew bootJar
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2.2.0
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v29.1
    -
      name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: madwind/cdnserver:latest
